spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddlAuto: create-drop
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernates.dialect.PostgreSQLDialect

